name: Chrome NodeJS
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - chrnodejs/**

jobs:
  push:
    name: "esdock:chrnodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [12, 14, 16, 18, 20, 22]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./chrnodejs
          file: ./chrnodejs/${{ matrix.tag }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/fishyspop/esdock:chrnodejs_${{ matrix.tag }}
