name: Chrome NodeJS
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - chrnodejs/**

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [12, 14, 16, 18, 20, 22]

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/fishyspop/esdock:chrnodejs_${{ matrix.tag }}
            ghcr.io/fishyspop/esdock:latest
